{% set version = "0.4" %}
{% set ot_version = "1.10" %}

package:
  name: otsvm
  version: {{ version }}

source:
  fn: otsvm-{{ version }}.tar.gz  # [not win]
  url: https://github.com/openturns/otsvm/archive/v{{ version }}.tar.gz  # [not win]
  sha256: 14166f7bb0da798a13d834e0b336038dd063252dc24ca91165236caddaf04083

  fn: otsvm-{{ version }}-py2.7-i686.exe  # [win32 and py27]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otsvm-{{ version }}-py2.7-i686.exe  # [win32 and py27]
  sha256: 14166f7bb0da798a13d834e0b336038dd063252dc24ca91165236caddaf04083

  fn: otsvm-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otsvm-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  sha256: 14166f7bb0da798a13d834e0b336038dd063252dc24ca91165236caddaf04083

  fn: otsvm-{{ version }}-py3.5-i686.exe  # [win32 and py35]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otsvm-{{ version }}-py3.5-i686.exe  # [win32 and py35]
  sha256: 14166f7bb0da798a13d834e0b336038dd063252dc24ca91165236caddaf04083

  fn: otsvm-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otsvm-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  sha256: 14166f7bb0da798a13d834e0b336038dd063252dc24ca91165236caddaf04083

  fn: otsvm-{{ version }}-py3.6-i686.exe  # [win32 and py36]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otsvm-{{ version }}-py3.6-i686.exe  # [win32 and py36]
  sha256: 14166f7bb0da798a13d834e0b336038dd063252dc24ca91165236caddaf04083

  fn: otsvm-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otsvm-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  sha256: 14166f7bb0da798a13d834e0b336038dd063252dc24ca91165236caddaf04083

build:
  number: 0

requirements:
  build:
    - toolchain
    - python
    - cmake  # [not win]
    - swig  # [not win]
    - openturns  # [not win]

  run:
    - python
    - openturns

test:
  imports:
    - otsvm

about:
  home: http://openturns.org/
  license: LGPL3
  license_file: COPYING.LESSER  # [not win]
  summary: SVM module

extra:
  recipe-maintainers:
    - jschueller
