{% set version = "0.5" %}

package:
  name: otsvm
  version: {{ version }}

source:
  fn: otsvm-{{ version }}.tar.gz
  url: https://github.com/openturns/otsvm/archive/v{{ version }}.tar.gz
  sha256: ef92d0749628e667ffa6875dcdc8886af922306759ed8b51ae20c3f9dcc71c08

build:
  number: 0

requirements:
  build:
    - cmake  # [not win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
  host:
    - python
    - swig  # [not win]
    - openturns  # [not win]
  run:
    - python
    - openturns

test:
  imports:
    - otsvm

about:
  home: http://openturns.org/
  license: LGPL3
  license_file: COPYING.LESSER
  summary: SVM module

extra:
  recipe-maintainers:
    - jschueller
