{% set version = "0.4" %}
{% set ot_version = "1.11rc1" %}

package:
  name: otsvm
  version: {{ version }}

source:
  fn: otsvm-{{ version }}.tar.gz  # [not win]
  url: https://github.com/openturns/otsvm/archive/v{{ version }}.tar.gz  # [not win]
  sha256: 14166f7bb0da798a13d834e0b336038dd063252dc24ca91165236caddaf04083  # [not win]

  fn: otsvm-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otsvm-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  sha256: 765a7f17b1f6eb31d8b5325632ccf3bb03fa537a158d2b1d08ae4cfc117bbe98  # [win64 and py27]

  fn: otsvm-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otsvm-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  sha256: dbba481566ab00baea47679101301bf168113070719b7705a2a5ce69ed043bcf  # [win64 and py35]

  fn: otsvm-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otsvm-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  sha256: 1ae9254ceaef60437b89416d4e2485610821057d095abd4179cee7236f87065e  # [win64 and py36]

build:
  number: 1

requirements:
  build:
    - cmake  # [not win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
  host:
    - python
    - swig  # [not win]
    - openturns  # [not win]
  run:
    - python
    - openturns

test:
  imports:
    - otsvm

about:
  home: http://openturns.org/
  license: LGPL3
  license_file: COPYING.LESSER  # [not win]
  summary: SVM module

extra:
  recipe-maintainers:
    - jschueller
