{% set version = "0.17" %}

package:
  name: otsvm
  version: {{ version }}

source:
  fn: otsvm-{{ version }}.tar.gz
  url: https://github.com/openturns/otsvm/archive/v{{ version }}.tar.gz
  sha256: 5d5ac24a5f7e873a8851363a3d0ad3f11633e0501e9bcf35acd508c99517c849

build:
  number: 2
  run_exports:
    - {{ pin_subpackage('otsvm', max_pin='x.x') }}
  python_version_independent: true  # [is_abi3]
  skip: True  # [is_abi3 and not is_python_min]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - make  # [unix]
    - ninja  # [win]
    - swig
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python-abi3  # [is_abi3]
    - python
    - openturns
  run:
    - python

test:
  requires:
    - abi3audit  # [is_abi3]
  imports:
    - otsvm
  commands:
    - abi3audit $SP_DIR/otsvm/_otsvm.so -s -v --assume-minimum-abi3 3.10  # [unix and is_abi3]

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: SVM module

extra:
  recipe-maintainers:
    - jschueller
