{% set version = "0.10" %}

package:
  name: otsvm
  version: {{ version }}

source:
  fn: otsvm-{{ version }}.tar.gz
  url: https://github.com/openturns/otsvm/archive/v{{ version }}.tar.gz
  sha256: 835926d4c8adc37e0809577babb21e2103973537cd49efab07c9172ac7868482

build:
  number: 2
  run_exports:
    - {{ pin_subpackage('otsvm', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - curl  # [win]
  host:
    - python
    - openturns 1.18*
  run:
    - python
    - openturns 1.18*

test:
  imports:
    - otsvm

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: SVM module

extra:
  recipe-maintainers:
    - jschueller
