{% set version = "0.11" %}

package:
  name: otsvm
  version: {{ version }}

source:
  fn: otsvm-{{ version }}.tar.gz
  url: https://github.com/openturns/otsvm/archive/v{{ version }}.tar.gz
  sha256: a1cc617003686cbfcb31b4ad2feb45c715260e91866f8f23c0be3d949b09a8f2

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('otsvm', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make  # [unix]
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - curl  # [win]
  host:
    - python
    - openturns 1.19*
  run:
    - python
    - openturns 1.19*

test:
  imports:
    - otsvm

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: SVM module

extra:
  recipe-maintainers:
    - jschueller
