{% set version = "0.17" %}

package:
  name: otsvm
  version: {{ version }}

source:
  fn: otsvm-{{ version }}.tar.gz
  url: https://github.com/openturns/otsvm/archive/v{{ version }}.tar.gz
  sha256: 5d5ac24a5f7e873a8851363a3d0ad3f11633e0501e9bcf35acd508c99517c849

build:
  number: 0
  skip: true  # [win and py==314]
  run_exports:
    - {{ pin_subpackage('otsvm', max_pin='x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - make  # [unix]
    - swig
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - curl  # [win]
  host:
    - python
    - openturns
  run:
    - python
    - openturns

test:
  imports:
    - otsvm

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: SVM module

extra:
  recipe-maintainers:
    - jschueller
