appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: GixWCsvy+VVx7FSJtQvtXZuETHrffpbjy0CbwtwzLoFJsWxPdE/Ak0aDO2G7IG6w5ApiaOr62o/lugbEE1KPTPDnRkWXr3L3VH91qKQy1R2tYoBMeoXOsVCBrbeG6gYEoZ0wloqB6ATuoJam1aE9VUSW0RAsyHF1cvTMufs5EN0qSK5+A7mz46+xZMtWNSNcDKR30Kb5C9LuN+Sft+2WoTtQ31uqhKnbvr9eX6Qesn0LLYHD058hjuJm3QB1WaxuFus+vyzHVPzbRHudfA5bdQgCMgX4SnP4+2wCc/mu2ts4I5g2uRyyCBEClD4xE+YVoq1hYdp/3/K67VTz7ETSLBfryhFZy61Q0HfvLXYzCgfKefc3oKWsL1mJVwsGaPMPRyhBojw9w1C1v8MM1DwXi41TfV/Vytehgv1iWsiww3AJZcrKjhEorUViKpjbFsg5+w375YrdlfTOO23+sH7uIxX2EYP2FHrwJsHLvRn/zmLLKci2hEVxBKKchKUbFVuOk2Rl+MnWoKvqragEycya9P/JBOl7MCpsZtH58EwrTrTEbqjjQ9K3S92UE+6SFaYlqjcuHbOd90Lb++JRWHwkYxYtNvZgUnneihIQEDCdobE31uSMA4LQ6o0R8rCVsI3TmXQ5gbjW0ESRqTSswORLBPa0fklyAWZxoKw2TutaJgw=}
provider:
  win: azure
conda_forge_output_validation: true
