travis:
  secure:
    BINSTAR_TOKEN: O+SVNrFUW0iUGKBroc5LeMGcty3J6qQOBpfewlvdTVBnpulvZahYFghq9h65saRVc1TYuXv08AwXcskWklP/oXfT6bMaiCZlJP/HvDErZyCg+qJe8UCqQF2b8LhFDedodTAnQzCs3FvPAhAct65gBopqZ0FdGu2e85z8n1mkqdxHbAeF+GlYfgN1c5nussaPENGltF788mPJswiMEi+Sy8oHq2H8dewZyqNoCILYUnkNfZ4Pz6cZRm0S25p2mukRyM4O1e7yK0elm1oPydsxRKQ0J7FHyVPAoEKuDdhAUin6CwnNDK4eWUlRyM0RKF8S+eUMwcRXokJLXeknMkNZh81y2a0eJExk2c1dp2L4WHGfAqkJgQ1fYM+OXu5dU3s3s/dhhapgc9IdhyUbDoLR5pPr+vCFw4llTx/fmt6ufxouCVWdLX9P/iBDPcXJBzNl7vRVPAAo71V/b2A7PjQ/G05VSozUmMStqhJsDel5ybraPeaWMSo6Vwrm3GhnLQ29JYthpWZ2SdieOXSz5TGFKZfehqKbnyx6dZHSZsECJb13pCumVBVgnEzyoarj+KfCyIZ+w76pJRm/BIgLWS5BdWNBBoOdK0BgXPQ0uXb+VUxBdLfzgS7on9ilbai+MHJD+Yp3QIqWyHz51ULDvP78MrXmKcXCybOnqC1LnQuBTW8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
